# Application Name
spring.application.name=security

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=R@jan2002
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration for PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Disable Spring Security's default user (Optional, since we are using custom authentication)
spring.security.user.name=jeeva
spring.security.user.password=1234


jwt.secret=yflDZC1+eJkW2jR5H3I901sYuatTfrPOxTeJKINLDSk=

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = jeevasmailservice@gmail.com
spring.mail.password = stbu kdtb lppl sngd
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable=true
